#!/usr/bin/env python

import os
virtual_env_file = '/services/ic-tools/python36-virtualenv/bin/activate_this.py'
execfile(virtual_env_file, dict(__file__=virtual_env_file))

# IMPORTS
import time, sys, ldap, boxsdk, os, ldap3
from ldap3 import Server, Connection, ALL
#import ldap.modlist as modlist
from boxsdk import JWTAuth, Client
from boxsdk.exception import BoxAPIException
from ic_functions36 import *
global valid_date
yes = set(['yes','y','ye',''])
no = set(['no','n'])

# ENVIRONMENT AND VARIABLES
uiucDomain = XXXXXXXX
uiucLdapBindDn = 'cn=XXXXXX,OU=XXXXXX,DC=XXXXXX,DC=XXXXXX,DC=XXX'
uiucRootDn = 'DC=XXXXXX,DC=XXXXXX,DC=XXX'
uiucGuestDn = 'cn=XXXXXX,OU=XXXXXX,DC=XXXXXX,DC=XXXXXX,DC=XXX'
uiucLdapBindPw = XXXXXXXX
uiucLdapHost = 'ldaps://XXXXXX.XXXXXX.XXX'
uiucGroupDn = 'cn=XXXXXX,OU=XXXXXX,DC=XXXXXX,DC=XXXXXX,DC=XXX'
uiucLdapPort = int('636')
uiucGuestUserLdifAttr = {}
now = int(time.time())
thisYear = int(time.strftime('%Y'))
boxAuth = JWTAuth.from_settings_file('/XXXXXX/XXXXXX/XXXXXX/XXXXXX.json')
boxClient = Client(boxAuth)
boxGuestParentFolderId = 'XXXXXXXX'
boxGuestParentFolder = boxClient.folder(folder_id = boxGuestParentFolderId).get()
boxPerms = 'Viewer'
boxGuestCredentialsFilePath = '/XXXXXX/XXXXXX/XXXXXX/XXXXXX' + str(now) + '.txt'

# CONNECT TO LDAP
try:
    uiucLdapServer = Server(uiucLdapHost, port=uiucLdapPort, use_ssl=True, get_info=ALL)
    uiucLdapConn = Connection(uiucLdapServer, uiucLdapBindDn, uiucLdapBindPw, auto_bind=True)
    uiucLdapConn.bind()
    print('=== SUCCESSFULLY CONNECTED TO LDAP ===')
except:
    print('=== NOT CONNECTED TO LDAP ===')

# CREATE GUEST ACCOUNT
if uiucLdapConn.bound == True:
    try:
        uiucGuestUser = input('New Guest Username: ')
        uiucGuestUserDn = 'CN=' + uiucGuestUser + ',' + uiucGuestDn
        uiucGuestUserFirstName = input('First Name: ')
        uiucGuestUserLastName = input('Last Name: ')
        uiucGuestCaRequest = input('CA Request: ')
        uiucGuestRequestor = input('CA Requestor Email: ')
        print('Please enter a day in this format:  YYYY-MM-DD')
        uiucGuestAccountExpire = get_date()
        uiucGuestAccountExpireEpoch = str(get_epoch(uiucGuestAccountExpire))
        uiucGuestUserPw = str(gen_guest_pwd())
        boxGuestCredentialsFilename = str(uiucGuestCaRequest + '.txt')
        uiucGuestUserLdifAttr = {}
        uiucGuestUserLdifAttr['objectClass'] = ['top', 'Person', 'organizationalPerson', 'user']
        uiucGuestUserLdifAttr['cn'] = uiucGuestUser
        uiucGuestUserLdifAttr['sAMAccountName'] = uiucGuestUser
        uiucGuestUserLdifAttr['userAccountControl'] = '514'
        uiucGuestUserLdifAttr['givenName'] = uiucGuestUserFirstName
        uiucGuestUserLdifAttr['sn'] = uiucGuestUserLastName
        uiucGuestUserLdifAttr['description'] = uiucGuestCaRequest
        uiucGuestUserLdifAttr['accountExpires'] = uiucGuestAccountExpireEpoch
        myResult = uiucLdapConn.add(uiucGuestUserDn, attributes=uiucGuestUserLdifAttr)
        uiucLdapConn.extend.microsoft.modify_password(uiucGuestUserDn, uiucGuestUserPw)
        uiucLdapConn.modify(uiucGuestUserDn, {'primaryGroupID':(2,['513'])})
        uiucLdapConn.modify(uiucGuestUserDn, {'userAccountControl':(2,['512'])})
        uiucLdapConn.extend.microsoft.unlock_account(uiucGuestUserDn)
        print('=== AD ACCOUNT SUCCESSFULLY CREATED ===')
    except:
        print('=== AD ACCOUNT NOT CREATED ---')
else:
    print('=== LDAP NOT CONNECTED ===')

# WRITE CREDENTIALS TO TEMP FILE
try:
    with open(boxGuestCredentialsFilePath, 'a') as boxGuestCredentialsFilePathWriteable:
        boxGuestCredentialsFilePathWriteable.write('Username:  ' + uiucGuestUser + '\n')
        boxGuestCredentialsFilePathWriteable.write('Password:  ' + uiucGuestUserPw + '\n')
        boxGuestCredentialsFilePathWriteable.write('Expires:   ' + uiucGuestAccountExpire + '\n')
    boxGuestCredentialsFilePathWriteable.close()
    print('=== CREDENTIALS FILE SUCCESSFULLY CREATED ===')
except:
    print('=== CREDENTIALS FILE NOT CREATED ===')

# CREATE GUEST SUBFOLDER IN BOX
try:
    boxGuestFolderName = uiucGuestCaRequest
    boxCreateGuestFolder = boxClient.folder(boxGuestParentFolderId).create_subfolder(boxGuestFolderName)
    boxGuestFolderId = int(boxCreateGuestFolder['id'])
    print('=== GUEST FOLDER SUCCESSFULLY CREATED IN BOX ===')
except:
    print('=== GUEST FOLDER NOT CREATED ===')

# UPLOAD TEMP FILE TO GUEST SUBFOLDER
try:
    boxClient.folder(boxGuestFolderId).upload(boxGuestCredentialsFilePath, boxGuestCredentialsFilename)
    print('=== CREDENTIALS FILE SUCCESSFULLY UPLOADED ===')
except:
    print('=== CREDENTIALS FILE NOT UPLOADED ===')

# SHARE FOLDER TO REQUESTOR
try:
    tempResult = boxClient.folder(boxGuestFolderId).create_shared_link()
    boxClient.folder(boxGuestFolderId).collaborate_with_login(login=uiucGuestRequestor, role='Viewer')
    boxSharedLink = str(tempResult['shared_link']['url'])
    print('=== CREDENTIALS FILE SUCCESSFULLY SHARED ===')
    print('=== Shared link:  ' + boxSharedLink)
except:
    print('=== CREDENTIALS FILE NOT SHARED ===')
